### PR TITLE
CODE RUB: HttpExchange V2.10.3 Abstraction Refinement

### LINKED ISSUE #59: CODE RUB: Foundations - `GetAsync` - v2.10.3 Abstraction Refinements, Additions

### PR DESCRIPTION
**Pull request by aosunlana**
Closes #59

### CODE REVIEW

**Review by LBoullosa — COMMENTED** [review]
Methods should be name with Async if they are async

**Review by LBoullosa — DISMISSED** [review]

**Comment by glhays** [comment]
@aosunlana, see this section in The Standard and apply as well. https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.1%20Foundations/2.1%20Foundations.md#213111-dynamic-rules
@LBoullosa FYI

**Comment by aosunlana** [comment]
> @aosunlana, see this section in The Standard and apply as well. https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.1%20Foundations/2.1%20Foundations.md#213111-dynamic-rules @LBoullosa FYI

@glhays  @LBoullosa Kindly take a review

**Review by glhays — APPROVED** [review]
LGTM

**Pull request merged**
